### ISSUE TITLE
incompatibility crash

### ISSUE THREAD

**Issue by Aces-and-Jacks** [isXander/Zoomify#100]
<img width="1126" alt="Screen Shot 2022-11-19 at 2 57 10 PM" src="https://user-images.githubusercontent.com/106651342/202869145-eaf6ca85-c7a3-4186-a789-5f224afef023.png">

https://mclo.gs/QyK1jHa

**Comment by isXander** [comment]
You need to update fabric-language-kotlin. Let me know if this fixes the issue.

**Comment by Aces-and-Jacks** [comment]
I'm using the quilt mod loader so I use Quilt Kotlin Libraries

**Comment by Aces-and-Jacks** [comment]
and your mod says compatible with quilt so...

**Comment by Deftu** [comment]
It would seem QKL is providing an old version of FLK. Wait for them to update.
