### ISSUE TITLE
Zoomify broken for 1.19.2

### ISSUE THREAD

**Issue by BeggarJr** [isXander/Zoomify#116]
Minecraft crashing when trying to open Zoomify settings menu, settings menu not visible in mod menu interface. Possible reason: For Zoomify 2.9.0 (1.19-1.19.3) all other dependencies make sense, but for Fabric API it says that the 1.19.3 version is required (not the 1.19.2 version)

Similar issue to #86

**Comment by osfanbuff63** [comment]
Can confirm. Was Zoomify 1.19.2 ever recompiled with the new YACL jar? I think that could be the issue here...it's likely as simple as a recompile but we all know how xander feels about backports haha

**Comment by FibreTTP** [comment]
Seeing this with Zoomify 2.9.0 and YACL 2.2.0 on Quilt and Fabric 1.19.2.

Logs if needed (Fabric):
https://gist.github.com/FibreTTP/3cae5164545d0ced34bf4b62e0cb9652

Zoomify 2.6.0 seems to work with YACL 1.4.3.

**Comment by isXander** [comment]
Don't update to the backported YACL 2.2.0-for-1.19.2, none of my old 1.19.2 mods updated to this and are now unsupported.
