### ISSUE TITLE
Make mouse sensitivity adaptive to zoom scale

### ISSUE THREAD

**Issue by Madis0** [isXander/Zoomify#117]
I suggest adding an option that would adjust the sensitivity of the "zoom cursor" according to how zoomed in it is. Higher zoom = lower sensitivity.

**Comment by isXander** [comment]
What do you mean by zoom cursor?

**Comment by Madis0** [comment]
The area displayed on screen as zoomed.

**Comment by isXander** [comment]
Like a screen magnifier like Ok Boomer?

**Comment by Madis0** [comment]
No, it is about the smoothness of the scrolling on normal zoom.

**Comment by isXander** [comment]
Isn't this relative sensitivity?

**Comment by Madis0** [comment]
> I guess it is, but it's far from "accurate" relative zoom, just compare ok (z/b)oomer straight with zoomify and you'll understand what am I talking about

**Comment by isXander** [comment]
Relative sensitivity is this. The higher the FOV divisor, the lower the sensitivity, the strength of this is configurable with a slider.
