### ISSUE TITLE
Crash when opening Modmenu 

### ISSUE THREAD

**Issue by Kai-mbe** [isXander/Zoomify#122]
When I click 'MODS' to open Modmenu I get an immediate 'Saving world...' and crash. This only occurs after 10ish minutes in the world. 

I get this error from a few of your mods (zoomify, debugify, and cull-less-leaves):

> [22:06:47] [Render thread/ERROR]: Error from mod 'zoomify'
java.lang.IncompatibleClassChangeError: Found interface dev.isxander.yacl.api.YetAnotherConfigLib$Builder, but class was expected

As well as an error from You're in Grave Danger:

> [22:06:47] [Render thread/ERROR]: Error from mod 'yigd'
java.lang.ArrayIndexOutOfBoundsException: Index -1 out of bounds for length 129

Which seems to be the error actually causing the crash, but wanted to raise the issue here too in case it's an incompatibility.
[latest.log](https://github.com/isXander/Zoomify/files/10777214/latest.log)

**Comment by isXander** [comment]
You need to downgrade to YetAnotherConfigLib 1.x
