### ISSUE TITLE
Custom animation graphs (curves) [Feature request]

### ISSUE THREAD

**Issue by Mark1ed** [isXander/Zoomify#131]
https://user-images.githubusercontent.com/108518311/227532631-eca28ea0-cc49-4694-bb1d-457a1dcec441.mp4

"[Smooth Swapping](https://www.curseforge.com/minecraft/mc-mods/smooth-swapping)" mod has animated curves (graphs) in it's config. And I'd like to use my graphs instead of the ones in the zoomify config. To add a reference point, you need to press the right mouse button in the place where it needs to be created. To delete, you need to click the right mouse button on the point again. to move the anchor point, you need to press and hold it, and then move it to where you need it

**Comment by isXander** [comment]
I don't really see the need for such an advanced feature such as this when there are already so many transitions. If you want one in particular, just ask!
