### ISSUE TITLE
Zoomigy keep's crashing

### ISSUE THREAD

**Issue by IDontNow2** [isXander/Zoomify#133]
As soon I press C the game crashes

**Comment by isXander** [comment]
log?

**Comment by IDontNow2** [comment]
No log it’s when there is a lot of mods
The  @command /zommify crashes too

**Comment by isXander** [comment]
There is always a log. The crashlog.

**Comment by IDontNow2** [comment]
[Crash log.txt](https://github.com/isXander/Zoomify/files/11171833/Crash.log.txt)

**Comment by IDontNow2** [comment]
sorry i couldn't have connection for a little time

**Comment by isXander** [comment]
Downgrade to YACL 1.x
