### ISSUE TITLE
Mod Menu and /zoomify command not working

### ISSUE THREAD

**Issue by Skilloir** [isXander/Zoomify#147]
1.19.4 MC Fabric
When I try to go through Mod Menu to change a setting it gives an error
When I try to run the /zoomify command the game crashes, I tried different versions of Zoomify and Mod Menu with no luck
any fix?(url)

[https://imgur.com/a/eOjX2Hh]

**Comment by clasherrr** [comment]
same

**Comment by Speedwy** [comment]
I actually just got this exact error as well! I hope it gets fixed soon...

**Comment by Speedwy** [comment]
Back 15 minutes later, I found a temporary fix. By installing an older version of Yet Another Config Lib, it starts working again. The version i used to get the fix was 2.5.0.

https://github.com/isXander/YetAnotherConfigLib/releases/tag/2.5.0%2B1.19.4

**Comment by isXander** [comment]
Make sure YACL is up to date
