### ISSUE TITLE
[MC 1.19.4 Fabric] Crashes when Minecraft is loading

### ISSUE THREAD

**Issue by Silicon7921** [isXander/Zoomify#148]
**Minecraft crashed when loading Zoomify.
I removed Zoomify then Minecraft stopped crashing and loads well.**

java.lang.RuntimeException: Could not execute entrypoint stage 'client' due to errors, provided by 'zoomify'!
So I think it may be a bug of Zoomify. 

**The logfiles in the"logs" folder:**
[crash-2023-06-05_20.38.52-client.txt](https://github.com/isXander/Zoomify/files/11652603/crash-2023-06-05_20.38.52-client.txt)
[latest.log](https://github.com/isXander/Zoomify/files/11652604/latest.log)

**This is the json file of Minecraft:**
[1.19.4-Fabric 0.14.19.json.txt](https://github.com/isXander/Zoomify/files/11652611/1.19.4-Fabric.0.14.19.json.txt)

If it is a bug of Zoomify, I hope it can be fixed soon. If it is not a bug, Can you please tell me what caused the crashes?
Thank you.

**Comment by Silicon7921** [comment]
BTW I added lots of mods so it may be a mod conflict problem.

**Comment by Silicon7921** [comment]
WTF i know what happened now
"Caused by: java.lang.ClassNotFoundException: dev.**isxander.yacl**.api.OptionFlag"
It is caused by YetAnotherConfigLib
It conflicts with YACL3.0.0 BETA

**Comment by Silicon7921** [comment]
I changed to YACL2.5.1 and it is fixed now
So it is caused by 2 mods from the same creator

**Comment by NorthernLaw1500** [comment]
Having the same issue, I'll have to revert YACL. Hopefully fixed when everything updates for 1.20!

**Comment by xXRinzlerrXx** [comment]
minecraft 1.19.4 quilt (qfapi-6.0.0-beta.9_qsl-5.0.0-beta.10_fapi-0.83.0_mc-1.19.4)
Zoomify-2.10.0 crashes in conjunction with yet-another-config-lib-fabric-3.0.1+1.19.4 and fabric-language-kotlin-1.9.4+kotlin.1.8.21

**Comment by TH3N3WN00B** [comment]
Same as above

https://paste.ee/p/NjQvq

**Comment by Makonede** [comment]
can repro

**Comment by huntears** [comment]
Same, can reproduce

**Comment by Shadowpudding** [comment]
I have the same issue with both Zoomify and YACL are on the newest version

**Comment by Silicon7921** [comment]
> I have the same issue with both Zoomify and YACL are on the newest version

just change YACL to the nearest stable version like 2.5.1

**Comment by Makonede** [comment]
zoomify 2.9.4/yacl 3.0.0 beta 1 seem to work fine for me

**Comment by TH3N3WN00B** [comment]
> zoomify 2.9.4/yacl 3.0.0 beta 1 seem to work fine for me

Zoomify 2.9.4 and YACL 3.01 work fine also with memoryleakfix 1.1.1

**Comment by isXander** [comment]
Make sure YACL is up to date.

**Comment by Makonede** [comment]
@isXander using latest YACL or latest zoomify crashes minecraft, that's the issue here

**Comment by isXander** [comment]
With zoomify 2.9.4
