### ISSUE TITLE
minecraft 1.19.4 quilt (qfapi-6.0.0-beta.9_qsl-5.0.0-beta.10_fapi-0.83.0_mc-1.19.4)

### ISSUE THREAD

**Issue by xXRinzlerrXx** [isXander/Zoomify#153]
minecraft 1.19.4 quilt 0.19.0 beta 17 (qfapi-6.0.0-beta.9_qsl-5.0.0-beta.10_fapi-0.83.0_mc-1.19.4)
Zoomify-2.10.0 crashes without even logging into the game in combination with yet-another-config-lib-fabric-3.0.1+1.19.4 and fabric-language-kotlin-1.9.4+kotlin.1.8.21

Zoomify-2.9.4 works stably

_Originally posted by @xXRinzlerrXx in https://github.com/isXander/Zoomify/issues/148#issuecomment-1583402295_

**Comment by isXander** [comment]
Continue to use 2.9.4. 2.10.0 has now been marked as incompatible with 1.19
