### ISSUE TITLE
Zoomify-2.10.0.jar on 1.19.3 not working

### ISSUE THREAD

**Issue by Cape-City** [isXander/Zoomify#155]
Hi,

the newest version for 1.19.3 MC fabric requires a v3 version of YetAnotherConfigLib which isn't available in the  CurseForge launcher.

The only newer version shown, isn't for 1.19.3:

![grafik](https://github.com/isXander/Zoomify/assets/122229367/0b418259-b2ff-49c6-99fa-a69adae242b2)

**Comment by isXander** [comment]
Continue to use Zoomify 2.9.4
