### ISSUE TITLE
Cant get zoomify to Zoom ?

### ISSUE THREAD

**Issue by Agoreon** [isXander/Zoomify#199]
Hi Guys,
I was switching from Optifine to Fabric for 1.20.5. Everything exept Zoomify works, ive tried Updating and Downgrading several mods and my friend has the exact same mods and versions installed as I do, but when loading into a world my Zoomify Mod just refuses to work what did I do wrong?
![image](https://github.com/isXander/Zoomify/assets/168362505/6d92c426-8676-4b68-84c6-273ef2831c91)
![image](https://github.com/isXander/Zoomify/assets/168362505/5dc16201-61f4-4316-ae85-d56de343a218)

**Comment by isXander** [comment]
Have you checked if there is a conflicting keybind?

**Comment by Agoreon** [comment]
OMG I genuinly feel so dumb, bc I recently reinstalled my Windows I did not think it would make a diffrence, because I never changed any Keybinds before reinstalling and after so no idea why there was a thing Binded to c all of the suddon xD Thank u so much the mod is a gamechanger !!
