### ISSUE TITLE
every version of zoomify after 1.3.1 is breaking on Quilt

### ISSUE THREAD

**Issue by DioEgizio** [isXander/Zoomify#20]
<img width="912" alt="image" src="https://user-images.githubusercontent.com/83089242/165585457-4d1ac18e-6c33-440f-8510-466f9af908a8.png">

latest.log: https://0x0.st/oTdo.txt

**Comment by isXander** [comment]
Is another mod shading Mixin Extras? Could you
a. try with just zoomify, does it work?
b. perform binary search of mods. (half out, if it works, half again, if not add half of the half back)

**Comment by DioEgizio** [comment]
Works with just zoomify+QSL+fabric language kotlin+cloth config api on quilt but adding Debugify makes it crash like that

**Comment by DioEgizio** [comment]
yes now it works! tysm
