### ISSUE TITLE
This mod with Controlify beta 9 doesn't load

### ISSUE THREAD

**Issue by Josh65-2201** [isXander/Zoomify#200]
## Logs
[latest.log](https://github.com/isXander/Zoomify/files/15443712/latest.log)

## Versions
Minecraft: 1.20.1
Mod loader: Quilt 0.26.0 beta 2
Zoomify: 2.13.4
Controlify: 2.0.0 beta 9

**Comment by rakantoh** [comment]
+1, controlify 2 B9 and zoomify 2.13.5 crash the game. 1.20.4 and 1.20.6 fabric

**Comment by TheCrafter8000** [comment]
+1, here is my log
[crash-2024-05-26_00.30.15-client.txt](https://github.com/isXander/Zoomify/files/15446091/crash-2024-05-26_00.30.15-client.txt)

**Comment by VirulentSlayer** [comment]
I'd like to add some (hopefully useful) info and logs.

FabricLoader 0.15.11
Fabric 1.20.1

Controlify-2.0.0-beta.9+1.20.1.jar
Zoomify-2.13.5+1.20.1.jar
YetAnotherConfigLib-3.4.2+1.20.1-fabric.jar

[crash-2024-05-26_19.09.17-client.txt](https://github.com/isXander/Zoomify/files/15448489/crash-2024-05-26_19.09.17-client.txt)

for the time being could you please suggest the correct working trio of these mods for 1.20.1 ;
controlify
zoomify
yacl

Thank you.

**Comment by Josh65-2201** [comment]
Controlify beta 8 works with the latest of the others

**Comment by VirulentSlayer** [comment]
Thanks @Josh65-2201, additionally I have managed to load up using the latest YACL and CONTROLIFY, by removing/disabling the latest Zoomify.

**Comment by isXander** [comment]
Use beta 10 of controlify
