### ISSUE TITLE
Infected release?

### ISSUE THREAD

**Issue by LightningPlayz94** [isXander/Zoomify#207]
Windows Defender immediately flagged the 2.14.0 for 1.21 release I downloaded from Modrinth as a trojan. I looked through my Microsoft folder as well to see if there were any sketchy stuff (as Fractureiser could still be a-bout) and I don't know for sure if it was but there was files with odd file extensions and stuff like that...
![image](https://github.com/isXander/Zoomify/assets/107431226/b03663b3-c94e-4bb0-b2da-b758a221f54d)

**Comment by blurrryyyy** [comment]
yeah same even on the modrinth app, the mod deletes itself after a couple seconds and when i tried running minecraft it gave me a bunch of errors in the crash log saying the same thing lol.

**Comment by akerS4I** [comment]
Downloaded 2.14.0 for minecraft 1.20.1 didn't have any issues with Windows Defender.
Checked 2.14.0 for both 1.20.1 and 1.21 in virustotal and it didn't detect anything suspicious.

**Comment by LightningPlayz94** [comment]
> yeah same even on the modrinth app, the mod deletes itself after a couple seconds and when i tried running minecraft it gave me a bunch of errors in the crash log saying the same thing lol.

Did you run a full scan on your computer using an antivirus? I’m just curious if it found anything.

**Comment by blurrryyyy** [comment]
> > yeah same even on the modrinth app, the mod deletes itself after a couple seconds and when i tried running minecraft it gave me a bunch of errors in the crash log saying the same thing lol.
> 
> Did you run a full scan on your computer using an antivirus? I’m just curious if it found anything.

i didnt run a full scan of my pc but when i tried launching minecraft with this mod, fabric loader gave me a log of errors and one of which said it might be a potential risk using the mod and it described it as a virus or a trojan. i cant seem to give enough proof since i cant replicate it anymore because the mod is working fine now

**Comment by LightningPlayz94** [comment]
> > > yeah same even on the modrinth app, the mod deletes itself after a couple seconds and when i tried running minecraft it gave me a bunch of errors in the crash log saying the same thing lol.
> > 
> > 
> > Did you run a full scan on your computer using an antivirus? I’m just curious if it found anything.
> 
> i didnt run a full scan of my pc but when i tried launching minecraft with this mod, fabric loader gave me a log of errors and one of which said it might be a potential risk using the mod and it described it as a virus or a trojan. i cant seem to give enough proof since i cant replicate it anymore because the mod is working fine now

Do you know if your computer is infected with something or not? Because after I ran a full scan on my computer there were at least 70 threats found.

**Comment by blurrryyyy** [comment]
> > > > yeah same even on the modrinth app, the mod deletes itself after a couple seconds and when i tried running minecraft it gave me a bunch of errors in the crash log saying the same thing lol.
> > > 
> > > 
> > > Did you run a full scan on your computer using an antivirus? I’m just curious if it found anything.
> > 
> > 
> > i didnt run a full scan of my pc but when i tried launching minecraft with this mod, fabric loader gave me a log of errors and one of which said it might be a potential risk using the mod and it described it as a virus or a trojan. i cant seem to give enough proof since i cant replicate it anymore because the mod is working fine now
> 
> Do you know if your computer is infected with something or not? Because after I ran a full scan on my computer there were at least 70 threats found.

i just ran a scan with malwarebytes, no its not infected... weird. but fr the jar file earlier did say it was malicious. i guess now the file is safe..?

**Comment by isXander** [comment]
This is a false positive. Make sure to update your malware definitions in defender.
