### ISSUE TITLE
[Feature Request] Allow even faster zoom animation.

### ISSUE THREAD

**Issue by IJustWantANamePlease** [isXander/Zoomify#32]
I noticed that maximum animation speed is pushed to 150% now, but I feel like it's still too slow. Is it possible to make that much faster (like the vanilla spyglass speed or even faster)?

**Comment by isXander** [comment]
Maybe it seems that way due to the transition you picked. Try an ease out rather than an in

**Comment by IJustWantANamePlease** [comment]
You're right, ease out does look better. Actually ease in is also good normally, the problem seems to be the animation is often slower. Maybe it's because of my computer.
