### ISSUE TITLE
Relative Sensitivity unavailable until manually change

### ISSUE THREAD

**Issue by Chucky2401** [isXander/Zoomify#35]
Hello,
I think I find a little issue.

The first time I configured the mod, I didn't find the setting *Relative Sensitivity* in Mod Menu.

After I set this option in the *.json* file to **true** instead of **false**, the option appeared in the settings menu.

![Imgur](https://i.imgur.com/t3KnQjrl.png)

![Imgur](https://i.imgur.com/bTzq9bYl.png)

Now, I'm able to swtich this option from the menu.

Thank you

**Comment by isXander** [comment]
![image](https://user-images.githubusercontent.com/43245524/172069919-eb42d384-75b5-4f4d-a466-1e41ad52f228.png)
cannot repeat. once the option is set back to false and you restart the game does the option hide again?

**Comment by isXander** [comment]
If you rename your config to `zoomify-backup.json` and reload the game, is it still there?

**Comment by Chucky2401** [comment]
Yeah, still there.
I don't understand, maybe something wrong with my instance.

Sorry to have bothered you for nothing.
I let you close this topic or if you want to ask me anything else.
