### ISSUE TITLE
Zoom sometimes just causes a rendering error

### ISSUE THREAD

**Issue by ReiaTheGeia** [isXander/Zoomify#39]
I was using the scroll zoom, zoomed out, to 'normal' manually, let go of the button to un-zoom, and then this occurred.
![2022-06-12_23 02 15](https://user-images.githubusercontent.com/58919834/173283430-205ef256-72a3-4e65-9b41-2df4d55c3810.png)

My settings are as following:
![2022-06-12_23 04 08](https://user-images.githubusercontent.com/58919834/173283491-918562d3-1667-44ae-9104-bc87f9064ae9.png)
![2022-06-12_23 04 11](https://user-images.githubusercontent.com/58919834/173283495-cfaa84e8-bb06-4d23-8e1f-d99d6b972e56.png)
![2022-06-12_23 04 13](https://user-images.githubusercontent.com/58919834/173283496-8c2f3519-cf09-49bc-ac4f-818636df5956.png)

**Comment by isXander** [comment]
I'd suggest
1. don't zoom out with the scroll zoom
2. use a different transition - ease out exp works great

I will be removing the ability to scroll out with scroll zoom
