### ISSUE TITLE
1.18.2 crashing after launching 1.19

### ISSUE THREAD

**Issue by PweSol** [isXander/Zoomify#40]
I successfully updated my game and my mods to 1.19 and played for a while. I then tried to launch 1.18.2 but the game crashes with the culprit being Zoomify. Upon investigating, it seems it is caused by zoomify.json config file. The 1.19 version is not backwards compatible with the 1.18.2 (Zoomify-1.6.0.jar) version.

It would be nice if the 1.19 config file could be updated to be compatible with its previous versions to avoid crashing. If it isn't possible, then a warning that this may happen should be added to the mod's description so people are aware of this issue.

**Comment by isXander** [comment]
This is due to the configuration being upgraded to a newer schema. In hindsight I should have implemented a schema property to prevent loading a newer config.

You can delete your config to resolve the issue.
