### ISSUE TITLE
Zoom animation speed scales with framerate

### ISSUE THREAD

**Issue by wwawaawwa** [isXander/Zoomify#41]
Title. This can make the experience inconsistent when moving between areas like a base and an open field, and can also be jittery when the framerate fluctuates.

**Comment by isXander** [comment]
Make sure you are up to date

**Comment by isXander** [comment]
The only thing that is jittery is your frame rate.
https://github.com/isXander/Zoomify/commit/e2ca5484eaeee541870c7478c19b65693c9dfe21

**Comment by wwawaawwa** [comment]
I am using 1.7.0
