### ISSUE TITLE
Max zoom beyond 100

### ISSUE THREAD

**Issue by supsm** [isXander/Zoomify#45]
Currently the max zoom slider is capped at 100, is it possible to increase this further?

**Comment by isXander** [comment]
Max scroll zoom is capped at 200?

**Comment by supsm** [comment]
Sorry, but I assume you understand my point? Sometimes I just want to zoom further but cannot because it is capped. Can you remove the limit altogether?

**Comment by isXander** [comment]
not really a good idea for UX

**Comment by isXander** [comment]
Behaviour switched to scroll zoom step amount
