### ISSUE TITLE
Presets

### ISSUE THREAD

**Issue by Madis0** [isXander/Zoomify#50]
I suggest adding two buttons:
"Reset to default" and "Reset to OptiFine-like"

The latter is described on https://github.com/Fabulously-Optimized/wiki/blob/main/en-us/give-up-optifine.md

**Comment by isXander** [comment]
Not possible with cloth config

**Comment by isXander** [comment]
I'm up to switching to a better settings lib if there is one.

**Comment by Madis0** [comment]
Hmm, I thought (manually built) Cloth Config was more flexible than its AutoConfig but you seem to be right. I'll let you know when I get an idea on how to do it.

**Comment by isXander** [comment]
It is but not that flexible

**Comment by TheKodeToad** [comment]
This was in OkZoomer even in older versions using cloth.

**Comment by isXander** [comment]
Implemented poorly using a dropdown setting.

**Comment by isXander** [comment]
Closing for now until either cloth adds buttons or someone suggests a better config library that can do this.
