### ISSUE TITLE
Replicating OK Zoomer

### ISSUE THREAD

**Issue by eyezahhhh** [isXander/Zoomify#51]
I've been told that this mod aims to replicate OK Zoomer's behaviour if the user so chooses. That being said, I don't think the experience is the same yet.

### Difference 1

Attached is a [comparison video](https://eyezah.com/final/Comparison.mp4) of OK Zoomer and Zoomify (recorded at 150fps and played back at 10% speed).

What's clear about this video is that that Zoomify has a more aggressive zoom IN and a less aggressive zoom OUT than OK Zoomer. OK Zoomer's logic behind this is sound:
- Smooth zooming in is usually for cosmetic use (in this case, most competitive players use instant zoom), and so the mod can afford to zoom in less aggressively in order to make that shift less jarring.
- Smooth zooming out, however, _needs_ to be snappy. Players stop zooming when they need to complete an activity, and so they should be able to transition out of zoom quickly, hence OK Zoomer's more aggressive zoom out.

Yes, I recorded this comparison at a high framerate and the difference is small, but it's very noticeable when playing. A variation of _ease out exp_ tuned with these differences in mind would be ideal in Zoomify.

### Difference 2

OK Zoomer lets you scroll-zoom in large steps (following the same transition curve rules as above), which lets the user scroll to easily replicated levels faster. Comparatively, Zoomify scroll-zooms in smaller increments, without smooth transitions.

You can see this difference in [this video](https://eyezah.com/final/ComparisonScroll.mp4) (60fps, 100% speed). Zoomify's settings were tuned to max zoom and max scroll speed in order to be comparable to OK Zoomer, by default, the scroll-zoom feels even more sluggish in Zoomify.

- Zoomify gives you finer control over your zoom.
- OK Zoomer lets you scroll-zoom faster.
- OK Zoomer's scroll-zoom transition is less jarring that Zoomify's.

To better replicate OK Zoomer, players should have the option to scroll-zoom the way OK Zoomer does.

<br/><br/>

As an OK Zoomer user trying to love Zoomify, these are the differences I've found. Besides that, the experience is identical.

**Comment by isXander** [comment]
Before releasing 2.0, could you re-examine the differences of both mods?

**Comment by eyezahhhh** [comment]
Got a couple things.

- Difference 1, mentioned above, has basically been resolved, with the ability to change the animation durations of zooming in/out separately. However, it would be great if we could change the transition type (exp, cubic, etc) separately for in/out (not a feature in okz iirc but I would use it to make the feel more consistent to okz).

- Difference 2 I feel is not quite there yet. The zoom steps in [this video](https://eyezah.com/final/weird-scroll-increments.mp4) start smaller than they used to. Maybe applying cubic to the transition has gone too far and now shrunk your first scroll zooms? Further tuning may be required.

- Unfortunately, [this jump](https://eyezah.com/final/jump.mp4) still seems to happen (RIP xander).

- Last thing for okz parity, okz lets you zoom _out_ from your initial zoom point, all the way out to your normal view. Would be great if zoomify had this ability.

But that's it! This is shaping up to be a huge update and definitely worthy of being named zoomify 2.0

**Comment by isXander** [comment]
- The things about the config changing will have to come later when I work on config 
  migration on my library, isXander/Settxi which handles config.
- You confirmed the jump is gone on discord
- You also confirmed that the zoom steps feel a lot more linear now
- "Minus" zoom steps won't really work on the current setup as the transition will turn them 
  back to positive.

All in all, this update has achieved everything I wanted it to (and more!). And I thank you very much for you feedback, I really appreciate it!
