### ISSUE TITLE
[Port Request]

### ISSUE THREAD

**Issue by SirOMGitsYOU** [isXander/Zoomify#71]
Hi,

Would it be possible to make a version available for forge 1.18.2?

**Comment by RaptaG** [comment]
Forge is not supported I doubt it will ever be.

**Comment by isXander** [comment]
Forge used to be supported in my other mod, Debugify, but it turns out Forge is bad and I will never use it or support it.

**Comment by TASC2** [comment]
> 我的另一个 Mod Debugify 曾经支持 Forge，但事实证明 Forge 很糟糕，我永远不会使用它或支持它。

Can Neoforge 1.21.1 be supported ? Please
