### ISSUE TITLE
Conflict detection is dumb

### ISSUE THREAD

**Issue by Madis0** [isXander/Zoomify#82]
Updated Zoomify to 2.4.0 and it popped up this toast:
![image](https://user-images.githubusercontent.com/8611110/186209446-611f7900-ff85-459b-9110-756bf1cb19b7.png)

However, FO unbinds Save Hotbar Activator and rebinds Zoomify's key, so there is actually no conflict whatsoever.
![image](https://user-images.githubusercontent.com/8611110/186209759-3d21f451-fe48-4e3a-a1e5-c958c6c59e28.png)
![image](https://user-images.githubusercontent.com/8611110/186209788-03acea97-d3ee-4d01-a1a4-a65998be4a1d.png)

Pls fix

MC 1.19.2, Fapi 0.60.0, Loader 0.14.9

**Comment by isXander** [comment]
Weird. This should only appear upon config creation of Zoomify anyway? Something must be very wrong...

**Comment by Madis0** [comment]
Well FO does not include Zoomify config, and those options get applied with YOSBR. 

So I'd say if you do check it at all (you announced that it only checks for zoomify config presence?), you should check, when the game loads, specifically whether the >oomify key has a conflict or not.

**Comment by isXander** [comment]
Hotfix released
