### ISSUE TITLE
Drop Cloth Config in favour of SpruceUI

### ISSUE THREAD

**Issue by isXander** [isXander/Zoomify#85]
As of Settxi 2.9.0, I can now easily move to SpruceUI.

## Why?
Shedaniel (creator of Cloth Config) has stated that they do not recommend using Cloth anymore as the API is bad, and is only supported because they don't want to rewrite REI config.

> "cloth config is bad, don't use it" - shedaniel

### OK Zoomer
As Zoomify becomes more and more advanced to fill the gap that was left on the migration to the Quilt Toolchain, the only major difference is the config screen. I don't want Zoomify to be seen as an OK Zoomer clone.

### UX
I fell the user experience in Cloth Config is marginally better than SpruceUI due to the way they handle categories. 

Cloth has a header which the user can always see and click on, making the user aware of the full capabilities immediately after opening the config.

On the SpruceUI side, the config feels busy with buttons everywhere (though they can be laid out more precisely) and categories are treated as sections, with the user having to scroll down to find the other categories. This flaw could be minimised by sorting the categories into their ascending complexity, basic users don't need to scroll, more advanced users can if they wish.

### Jar Size
Cloth Config is widely used in mods and is likely already included in modpacks or mod folders. Spruce, on the other hand, has no mod page on Curseforge nor Modrinth and relies on the mod to use Jar in Jar (though SpruceUI is more lightweight than Cloth).

## What is this issue for?
I would like to see some feedback from modpack developers and just regular users of Zoomify on what they think of the switch.

**Comment by Madis0** [comment]
As long as Cloth Config is maintained and switching to a different library would provide no benefits to you, just don't switch.

**Comment by isXander** [comment]
It is maintained but that's about it. I feel if the developer of cloth says don't use it I shouldn't use it...

**Comment by isXander** [comment]
And to prove a point of how easy it is to port: here is the port!
![image](https://user-images.githubusercontent.com/43245524/187258451-d8afd389-6237-4aca-978e-81c2937f5b38.png)

**Comment by Madis0** [comment]
> It is maintained but that's about it. I feel if the developer of cloth says don't use it I shouldn't use it...

We don't have the context though, I think he just said it as a joke.

**Comment by isXander** [comment]
@shedaniel could you confirm what you mean?

**Comment by shedaniel** [comment]
I don't care, use it if you want, don't use it if you don't want to

**Comment by RaptaG** [comment]
:) https://github.com/isXander/YetAnotherConfigLib
