### ISSUE TITLE
Switch from Cloth Config to YetAnotherConfigLibrary

### ISSUE THREAD

**Issue by Deftu** [isXander/Zoomify#89]
This issue is similar to #85 and as stated there,
> As of Settxi 2.9.0, I can now easily move to SpruceUI.
Though, in this context it'd be YACL instead.

## Why?
> Shedaniel (creator of Cloth Config) has stated that they do not recommend using Cloth anymore as the API is bad, and is only supported because they don't want to rewrite REI config.
> > "cloth config is bad, don't use it" - shedaniel

### Why not SpruceUI?
As stated by Xander, SpruceUI would make Zoomify feel more like a clone of OkZoomer. SpuceUI's UI is also much less verbose, and at least slightly harder to understand than the ones in both Cloth and YACL.

### Why YACL, instead of another library?
Xander made YACL himself, meaning if any issues were to arise he could fix it himself, and understands the library to it's fullest potential. As stated by many members of the Fabric Discord server, "it's the future of config", with it's sleek looking UI and more verbose nature.

**Comment by isXander** [comment]
Already working on it.
